-- Мелкие правки по спецификации (docs/SPEC_GAPS.md, пункты 13–16).

-- 13. Сторона детали «пара» (стойки, колодки — комплектом на ось)
ALTER TABLE parts DROP CONSTRAINT parts_side_check;
ALTER TABLE parts ADD CONSTRAINT parts_side_check CHECK (side IN ('LEFT', 'RIGHT', 'PAIR'));

-- 14. Короткое имя марки для подписи в плитке (23, 28): «Mercedes» вместо «Mercedes-Benz»
ALTER TABLE brands ADD COLUMN short_name VARCHAR(30);
UPDATE brands SET short_name = name;
UPDATE brands SET short_name = 'Mercedes' WHERE slug = 'mercedes-benz';
ALTER TABLE brands ALTER COLUMN short_name SET NOT NULL;

-- 15. Категория «Другое» — последней
INSERT INTO categories (slug, name_ru, name_kg, sort_order) VALUES ('other', 'Другое', 'Башка', 99)
ON CONFLICT (slug) DO NOTHING;

-- 16. Подсказки «что нужно» на экране 06 («+ Колодки», «+ Радиатор»). Выбранная подсказка запоминается
-- в запросе: по ней считается, что чаще спрашивают для этой модели и марки.
CREATE TABLE part_hints (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text_ru      VARCHAR(40) NOT NULL,
    text_kg      VARCHAR(40) NOT NULL,
    category_id  BIGINT      REFERENCES categories(id),
    -- базовый порядок, пока по машине нет запросов
    popularity   INT         NOT NULL DEFAULT 0
);

INSERT INTO part_hints (text_ru, text_kg, category_id, popularity)
SELECT h.text_ru, h.text_kg, c.id, h.popularity
FROM (VALUES
    ('Колодки',          'Колодкалар',          'brakes',     100),
    ('Стойки',           'Стойкалар',           'suspension',  90),
    ('Фара',             'Фара',                'lights',      80),
    ('Радиатор',         'Радиатор',            'cooling',     70),
    ('Масляный фильтр',  'Май чыпкасы',         'service',     60),
    ('Тормозные диски',  'Тормоз дисктери',     'brakes',      50),
    ('Рычаг',            'Рычаг',               'suspension',  45),
    ('Свечи',            'Шамдар',              'engine',      40),
    ('Ремень ГРМ',       'ГРМ курру',           'engine',      35),
    ('Бампер',           'Бампер',              'body',        30),
    ('Аккумулятор',      'Аккумулятор',         'electrics',   25),
    ('Сцепление',        'Илинишүү',            'transmission', 20)
) AS h(text_ru, text_kg, slug, popularity)
JOIN categories c ON c.slug = h.slug;

ALTER TABLE part_requests ADD COLUMN hint_id BIGINT REFERENCES part_hints(id) ON DELETE SET NULL;
CREATE INDEX idx_part_requests_hint ON part_requests (brand_id, created_at) WHERE hint_id IS NOT NULL;
