-- ─────────────────────────── ЗАЯВКИ НА УСЛУГИ И МАСТЕРА (спецификация, раздел 12) ───────────────────────────
-- Покупатель описывает проблему с машиной, заявку получают мастера нужной услуги, которые работают с маркой
-- и страной машины и находятся рядом; они отвечают «Могу помочь» или «Не моё». Время, продление и
-- статистика — как у запросов на запчасти.

ALTER TABLE users DROP CONSTRAINT users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check CHECK (role IN ('BUYER', 'SELLER', 'MASTER'));

-- ── машина: объём, топливо, страна (экраны 34–35)
ALTER TABLE cars
    ADD COLUMN engine_volume NUMERIC(2, 1) CHECK (engine_volume BETWEEN 0.5 AND 9.9),
    ADD COLUMN fuel          VARCHAR(10) CHECK (fuel IN ('PETROL', 'DIESEL', 'LPG_PETROL', 'HYBRID', 'ELECTRIC')),
    ADD COLUMN origin        VARCHAR(7) CHECK (origin IN ('JAPAN', 'USA', 'EUROPE', 'KOREA', 'UAE', 'UNKNOWN'));

-- ── справочник услуг (плитки 33, 38). needs_location — нужна точка на карте (эвакуатор, выездной мастер);
-- duration_min — сколько по умолчанию ждать отклики; urgent — пометка «Срочно»
CREATE TABLE service_types (
    code          VARCHAR(20) PRIMARY KEY,
    name_ru       VARCHAR(40) NOT NULL,
    name_kg       VARCHAR(40) NOT NULL,
    icon          VARCHAR(30) NOT NULL,
    sort_order    SMALLINT    NOT NULL,
    needs_location BOOLEAN    NOT NULL DEFAULT FALSE,
    duration_min  SMALLINT    NOT NULL DEFAULT 30,
    urgent        BOOLEAN     NOT NULL DEFAULT FALSE
);
INSERT INTO service_types (code, name_ru, name_kg, icon, sort_order, needs_location, duration_min, urgent) VALUES
    ('CAR_REPAIR',      'СТО и ремонт',       'СТО жана оңдоо',       'wrench',      1,  FALSE, 30, FALSE),
    ('TIRE_SERVICE',    'Шиномонтаж',         'Шиномонтаж',           'tire',        2,  FALSE, 30, FALSE),
    ('LPG',             'ГБО',                'ГБО',                  'gas',         3,  FALSE, 30, FALSE),
    ('TOW_TRUCK',       'Эвакуатор',          'Эвакуатор',            'tow',         4,  TRUE,  15, TRUE),
    ('CAR_WASH',        'Автомойка',          'Автожуугуч',           'wash',        5,  FALSE, 30, FALSE),
    ('AUTO_ELECTRIC',   'Автоэлектрик',       'Автоэлектрик',         'bolt',        6,  FALSE, 30, FALSE),
    ('BODY_PAINT',      'Кузов и покраска',   'Кузов жана боёо',      'paint',       7,  FALSE, 30, FALSE),
    ('DIAGNOSTICS',     'Диагностика',        'Диагностика',          'scan',        8,  FALSE, 30, FALSE),
    ('OIL_CHANGE',      'Замена масла',       'Май алмаштыруу',       'oil',         9,  FALSE, 30, FALSE),
    ('WHEEL_ALIGNMENT', 'Развал-схождение',   'Развал-схождение',     'alignment',   10, FALSE, 30, FALSE),
    ('TINTING',         'Тонировка',          'Тонировка',            'tint',        11, FALSE, 30, FALSE),
    ('MOBILE_MASTER',   'Выездной мастер',    'Чакыруу менен уста',   'van',         12, TRUE,  30, FALSE);

-- ── профиль мастера / СТО (экран 38). Один на пользователя; продавец может быть и мастером
CREATE TABLE masters (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id         BIGINT        NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    name             VARCHAR(60)   NOT NULL,
    avatar_media_id  BIGINT        REFERENCES media(id) ON DELETE SET NULL,
    phone            VARCHAR(16),
    address          VARCHAR(160)  NOT NULL,
    lat              DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lng              DOUBLE PRECISION NOT NULL CHECK (lng BETWEEN -180 AND 180),
    radius_km        SMALLINT      NOT NULL DEFAULT 5 CHECK (radius_km BETWEEN 1 AND 30),
    is_mobile        BOOLEAN       NOT NULL DEFAULT FALSE,
    all_brands       BOOLEAN       NOT NULL DEFAULT FALSE,
    open_from        TIME          NOT NULL DEFAULT '09:00',
    open_to          TIME          NOT NULL DEFAULT '19:00',
    work_days        SMALLINT      NOT NULL DEFAULT 127 CHECK (work_days BETWEEN 1 AND 127),
    is_accepting     BOOLEAN       NOT NULL DEFAULT TRUE,
    rating           NUMERIC(2, 1) NOT NULL DEFAULT 0,
    reviews_count    INT           NOT NULL DEFAULT 0,
    status           VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'BLOCKED')),
    block_reason     VARCHAR(300),
    -- если мастер работает на рынке
    container_id     BIGINT        REFERENCES containers(id),
    public_id        VARCHAR(16)   NOT NULL UNIQUE,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CHECK (open_from < open_to)
);
CREATE INDEX idx_masters_receiving ON masters (status, is_accepting);

CREATE TABLE master_services (
    master_id  BIGINT      NOT NULL REFERENCES masters(id) ON DELETE CASCADE,
    service    VARCHAR(20) NOT NULL REFERENCES service_types(code),
    PRIMARY KEY (master_id, service)
);
CREATE INDEX idx_master_services_service ON master_services (service, master_id);

CREATE TABLE master_brands (
    master_id  BIGINT NOT NULL REFERENCES masters(id) ON DELETE CASCADE,
    brand_id   BIGINT NOT NULL REFERENCES brands(id),
    PRIMARY KEY (master_id, brand_id)
);

-- пусто — любые машины
CREATE TABLE master_origins (
    master_id  BIGINT     NOT NULL REFERENCES masters(id) ON DELETE CASCADE,
    origin     VARCHAR(7) NOT NULL CHECK (origin IN ('JAPAN', 'USA', 'EUROPE', 'KOREA', 'UAE')),
    PRIMARY KEY (master_id, origin)
);

-- до 8 фото работ и места, первое — обложка
CREATE TABLE master_photos (
    master_id  BIGINT NOT NULL REFERENCES masters(id) ON DELETE CASCADE,
    sort       INT    NOT NULL CHECK (sort BETWEEN 0 AND 7),
    media_id   BIGINT NOT NULL REFERENCES media(id),
    PRIMARY KEY (master_id, sort)
);
CREATE INDEX idx_master_photos_media ON master_photos (media_id);

-- ── заявка (экраны 33–36): услуга, снимок машины, что случилось, когда и где
CREATE TABLE service_requests (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id               BIGINT        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    service                VARCHAR(20)   NOT NULL REFERENCES service_types(code),
    car_id                 BIGINT        REFERENCES cars(id) ON DELETE SET NULL,
    brand_id               BIGINT        NOT NULL REFERENCES brands(id),
    model_id               BIGINT        REFERENCES models(id),
    year                   SMALLINT,
    engine_volume          NUMERIC(2, 1),
    fuel                   VARCHAR(10)   CHECK (fuel IN ('PETROL', 'DIESEL', 'LPG_PETROL', 'HYBRID', 'ELECTRIC')),
    origin                 VARCHAR(7)    NOT NULL DEFAULT 'UNKNOWN'
        CHECK (origin IN ('JAPAN', 'USA', 'EUROPE', 'KOREA', 'UAE', 'UNKNOWN')),
    description            VARCHAR(500)  NOT NULL CHECK (char_length(description) >= 10),
    when_kind              VARCHAR(8)    NOT NULL CHECK (when_kind IN ('NOW', 'TODAY', 'TOMORROW', 'AT_TIME')),
    at_time                TIMESTAMPTZ,
    where_kind             VARCHAR(12)   NOT NULL CHECK (where_kind IN ('I_COME', 'MASTER_COMES', 'PICKUP_POINT')),
    lat                    DOUBLE PRECISION NOT NULL,
    lng                    DOUBLE PRECISION NOT NULL,
    address                VARCHAR(160),
    radius_km              SMALLINT      NOT NULL DEFAULT 5 CHECK (radius_km BETWEEN 1 AND 50),
    status                 VARCHAR(7)    NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'EXPIRED', 'CLOSED')),
    duration               VARCHAR(10)   NOT NULL CHECK (duration IN ('MIN_15', 'MIN_30', 'HOUR_1', 'HOUR_3', 'END_OF_DAY')),
    sent_at                TIMESTAMPTZ   NOT NULL,
    expires_at             TIMESTAMPTZ   NOT NULL,
    extended_times         SMALLINT      NOT NULL DEFAULT 0 CHECK (extended_times BETWEEN 0 AND 3),
    recipients_count       INT           NOT NULL DEFAULT 0,
    can_help_count         INT           NOT NULL DEFAULT 0,
    closed_with_master_id  BIGINT        REFERENCES masters(id) ON DELETE SET NULL,
    closed_at              TIMESTAMPTZ,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CHECK ((when_kind = 'AT_TIME') = (at_time IS NOT NULL))
);
CREATE INDEX idx_service_requests_buyer ON service_requests (buyer_id, created_at DESC);
CREATE INDEX idx_service_requests_expiring ON service_requests (expires_at) WHERE status = 'ACTIVE';
CREATE INDEX idx_service_requests_closed ON service_requests (closed_with_master_id, closed_at)
    WHERE closed_with_master_id IS NOT NULL;

-- до 5 фото к заявке
CREATE TABLE service_request_photos (
    request_id  BIGINT NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    sort        INT    NOT NULL CHECK (sort BETWEEN 0 AND 4),
    media_id    BIGINT NOT NULL REFERENCES media(id),
    PRIMARY KEY (request_id, sort)
);
CREATE INDEX idx_service_request_photos_media ON service_request_photos (media_id);

-- кому ушла заявка: лента мастера (39) и статистика заявки (37)
CREATE TABLE service_recipients (
    request_id    BIGINT      NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    master_id     BIGINT      NOT NULL REFERENCES masters(id) ON DELETE CASCADE,
    status        VARCHAR(9)  NOT NULL DEFAULT 'DELIVERED'
        CHECK (status IN ('DELIVERED', 'SEEN', 'CAN_HELP', 'NOT_MINE', 'EXPIRED')),
    distance_m    INT         NOT NULL,
    notified_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    seen_at       TIMESTAMPTZ,
    replied_at    TIMESTAMPTZ,
    PRIMARY KEY (request_id, master_id)
);
CREATE INDEX idx_service_recipients_feed ON service_recipients (master_id, notified_at DESC, request_id DESC);

-- отклик мастера (37, 39): один на заявку
CREATE TABLE service_offers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id    BIGINT       NOT NULL REFERENCES service_requests(id) ON DELETE CASCADE,
    master_id     BIGINT       NOT NULL REFERENCES masters(id) ON DELETE CASCADE,
    answer        VARCHAR(8)   NOT NULL CHECK (answer IN ('CAN_HELP', 'NOT_MINE')),
    price_from    INT          CHECK (price_from > 0),
    available_at  TIMESTAMPTZ,
    message       VARCHAR(300),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (request_id, master_id)
);
CREATE INDEX idx_service_offers_can_help ON service_offers (request_id, id) WHERE answer = 'CAN_HELP';

-- оценка мастеру при закрытии «Договорились»
CREATE TABLE master_reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    master_id   BIGINT      NOT NULL REFERENCES masters(id) ON DELETE CASCADE,
    buyer_id    BIGINT      REFERENCES users(id) ON DELETE SET NULL,
    request_id  BIGINT      UNIQUE REFERENCES service_requests(id) ON DELETE SET NULL,
    stars       SMALLINT    NOT NULL CHECK (stars BETWEEN 1 AND 5),
    tags        TEXT[]      NOT NULL DEFAULT '{}',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_master_reviews_master ON master_reviews (master_id, created_at DESC);

-- ── чат с мастером: у чата либо магазин, либо мастер
ALTER TABLE chats ALTER COLUMN shop_id DROP NOT NULL;
ALTER TABLE chats
    ADD COLUMN master_id           BIGINT REFERENCES masters(id) ON DELETE CASCADE,
    ADD COLUMN service_request_id  BIGINT REFERENCES service_requests(id) ON DELETE SET NULL,
    ADD CONSTRAINT chats_one_provider CHECK ((shop_id IS NULL) <> (master_id IS NULL));
CREATE UNIQUE INDEX uq_chats_service_request ON chats (buyer_id, master_id, service_request_id)
    WHERE service_request_id IS NOT NULL;
CREATE UNIQUE INDEX uq_chats_master_direct ON chats (buyer_id, master_id)
    WHERE master_id IS NOT NULL AND service_request_id IS NULL;
CREATE INDEX idx_chats_master ON chats (master_id, last_message_at DESC NULLS LAST, id DESC) WHERE master_id IS NOT NULL;

-- фото мастеров и заявок — в чистку неприкреплённых
ALTER TABLE media DROP CONSTRAINT media_purpose_check;
ALTER TABLE media ADD CONSTRAINT media_purpose_check
    CHECK (purpose IN ('PART', 'SHOP', 'AVATAR', 'REQUEST', 'REPLY', 'MASTER', 'SERVICE'));
