-- ─────────────────────────── АДМИНКА: СОТРУДНИКИ, ПРАВА, ЖУРНАЛ ───────────────────────────
-- Роль сотрудника — набор прав. Проверки в коде идут только по правам, роль в коде не сравнивается:
-- новая роль (оператор, модератор…) добавляется одной миграцией — строкой в CHECK и строками прав.

CREATE TABLE admin_members (
    user_id             BIGINT       PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    admin_role          VARCHAR(12)  NOT NULL CHECK (admin_role IN ('SUPER_ADMIN', 'MARKET_ADMIN')),
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    full_name           VARCHAR(120) NOT NULL,
    -- подпись в сайдбаре: «Администратор рынка»
    title               VARCHAR(80)  NOT NULL,
    -- bcrypt; NULL — пароль не задан, войти нельзя, пока не задан по SMS-коду
    password_hash       VARCHAR(72),
    password_changed_at TIMESTAMPTZ,
    created_by          BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_login_at       TIMESTAMPTZ
);

-- Права ролей. SUPER_ADMIN в коде имеет все права всегда — строки для него не нужны и не читаются.
CREATE TABLE admin_role_permissions (
    admin_role  VARCHAR(12) NOT NULL CHECK (admin_role IN ('SUPER_ADMIN', 'MARKET_ADMIN')),
    permission  VARCHAR(32) NOT NULL,
    PRIMARY KEY (admin_role, permission)
);

INSERT INTO admin_role_permissions (admin_role, permission)
SELECT 'MARKET_ADMIN', p FROM unnest(ARRAY[
    'DASHBOARD_VIEW', 'EXPORT_EXCEL',
    'SELLERS_VIEW', 'SELLERS_VERIFY', 'SELLERS_BLOCK', 'DISPUTES_RESOLVE',
    'MASTERS_VIEW', 'MASTERS_VERIFY', 'MASTERS_BLOCK', 'MASTERS_CREATE',
    'MARKET_VIEW', 'MARKET_EDIT', 'MARKET_MAP_PUBLISH', 'TENANTS_IMPORT',
    'REQUESTS_VIEW', 'REQUESTS_MANAGE',
    'COMPLAINTS_VIEW', 'COMPLAINTS_RESOLVE', 'CONTENT_REMOVE', 'SELLER_WARN',
    'DICTIONARIES_VIEW', 'DICTIONARIES_EDIT',
    'BROADCASTS_VIEW', 'BROADCASTS_SEND',
    'USERS_VIEW', 'USERS_BLOCK', 'PII_VIEW',
    'MESSAGE_USERS',
    'AUDIT_VIEW']) AS p;

-- Журнал: любое изменяющее действие админки. Строки не удаляются вместе с сотрудником.
CREATE TABLE admin_audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_id     BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    action       VARCHAR(40)  NOT NULL,
    entity_type  VARCHAR(24)  NOT NULL,
    entity_id    BIGINT,
    before       JSONB,
    after        JSONB,
    comment      VARCHAR(1000),
    ip           VARCHAR(45),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_admin_audit_created ON admin_audit_log (created_at DESC, id DESC);
CREATE INDEX idx_admin_audit_entity ON admin_audit_log (entity_type, entity_id, created_at DESC);
CREATE INDEX idx_admin_audit_admin ON admin_audit_log (admin_id, created_at DESC);

-- Администрация раньше хранилась в users.admin_role — переносим и убираем колонку
INSERT INTO admin_members (user_id, admin_role, full_name, title)
SELECT id,
       CASE admin_role WHEN 'SUPERADMIN' THEN 'SUPER_ADMIN' ELSE 'MARKET_ADMIN' END,
       COALESCE(NULLIF(trim(name), ''), phone),
       CASE admin_role WHEN 'SUPERADMIN' THEN 'Суперадмин' ELSE 'Администратор рынка' END
FROM users
WHERE admin_role IS NOT NULL;

ALTER TABLE users DROP COLUMN admin_role;

-- Сессии приложения и админки раздельные: refresh-токен одной не обменивается в другой
ALTER TABLE refresh_tokens
    ADD COLUMN audience VARCHAR(5) NOT NULL DEFAULT 'APP' CHECK (audience IN ('APP', 'ADMIN'));
