-- ─────────────────────────── АДМИНКА: ПРОДАВЦЫ (A2) И МАСТЕРА (A7) ───────────────────────────

-- «Отклонён»: администрация не подтвердила место (магазин) или профиль (мастер).
-- Отклонённый магазин не держит контейнер: место свободно для настоящего арендатора,
-- а продавец может выбрать другой контейнер и пройти проверку заново.
ALTER TABLE shops DROP CONSTRAINT shops_status_check;
ALTER TABLE shops ADD CONSTRAINT shops_status_check
    CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'BLOCKED', 'REJECTED'));
DROP INDEX uq_shops_container;
CREATE UNIQUE INDEX uq_shops_container ON shops (container_id) WHERE status <> 'REJECTED';

ALTER TABLE masters DROP CONSTRAINT masters_status_check;
ALTER TABLE masters ADD CONSTRAINT masters_status_check
    CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'BLOCKED', 'REJECTED'));

-- ФИО арендатора из базы рынка: «Арендатор по списку: Токтосунов А.»
ALTER TABLE containers ADD COLUMN tenant_name VARCHAR(120);

-- Импорт списка арендаторов (xlsx/csv): сначала предпросмотр, потом применение.
-- rows — разобранные строки с id контейнера, errors — [{line, message}].
CREATE TABLE tenant_imports (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name    VARCHAR(200) NOT NULL,
    uploaded_by  BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    status       VARCHAR(7)   NOT NULL DEFAULT 'PREVIEW' CHECK (status IN ('PREVIEW', 'APPLIED')),
    rows_total   INT          NOT NULL,
    rows_ok      INT          NOT NULL,
    rows_error   INT          NOT NULL,
    rows         JSONB        NOT NULL,
    errors       JSONB        NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    applied_at   TIMESTAMPTZ
);

-- Споры за контейнер: «Это мой контейнер» от того, чьё место занято в приложении.
-- claimant_shop_id — магазин заявителя, если он у него есть (часто нет: место-то занято).
CREATE TABLE container_disputes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    container_id      BIGINT        NOT NULL REFERENCES containers(id),
    claimant_user_id  BIGINT        REFERENCES users(id) ON DELETE SET NULL,
    claimant_shop_id  BIGINT        REFERENCES shops(id) ON DELETE SET NULL,
    current_shop_id   BIGINT        REFERENCES shops(id) ON DELETE SET NULL,
    text              VARCHAR(1000),
    status            VARCHAR(8)    NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RESOLVED')),
    -- кому достался контейнер: CURRENT — остаётся у того, кто стоит; CLAIMANT — у заявителя
    winner            VARCHAR(8)    CHECK (winner IN ('CURRENT', 'CLAIMANT')),
    resolution        VARCHAR(1000),
    resolved_by       BIGINT        REFERENCES users(id) ON DELETE SET NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    resolved_at       TIMESTAMPTZ
);
CREATE INDEX idx_container_disputes_open ON container_disputes (created_at) WHERE status = 'OPEN';
CREATE INDEX idx_container_disputes_container ON container_disputes (container_id, status);

-- Открытые заявки «Это мой контейнер» из жалоб переезжают в споры
INSERT INTO container_disputes (container_id, claimant_user_id, claimant_shop_id, current_shop_id, text, created_at)
SELECT c.target_id, c.author_id,
       (SELECT m.shop_id FROM shop_members m WHERE m.user_id = c.author_id AND m.role = 'OWNER'),
       (SELECT s.id FROM shops s WHERE s.container_id = c.target_id AND s.status <> 'REJECTED'),
       c.text, c.created_at
FROM complaints c
WHERE c.type = 'CONTAINER_CLAIM' AND c.status = 'OPEN' AND EXISTS (SELECT 1 FROM containers k WHERE k.id = c.target_id);
UPDATE complaints SET status = 'RESOLVED', resolution = 'Перенесено в споры за контейнер', resolved_at = now()
WHERE type = 'CONTAINER_CLAIM' AND status = 'OPEN';

-- Санкции администрации: история предупреждений и блокировок. «Предупреждён» — есть предупреждение,
-- действующее до active_until (90 дней).
CREATE TABLE sanctions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type   VARCHAR(6)    NOT NULL CHECK (target_type IN ('SHOP', 'MASTER', 'USER')),
    target_id     BIGINT        NOT NULL,
    type          VARCHAR(7)    NOT NULL CHECK (type IN ('WARNING', 'BLOCK', 'UNBLOCK')),
    reason        VARCHAR(1000),
    admin_id      BIGINT        REFERENCES users(id) ON DELETE SET NULL,
    active_until  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_sanctions_target ON sanctions (target_type, target_id, created_at DESC);

-- Жалоба на мастера — для отметки «Жалоба» в списке мастеров (модерация целиком — фаза 5)
ALTER TABLE complaints DROP CONSTRAINT complaints_type_check;
ALTER TABLE complaints ADD CONSTRAINT complaints_type_check
    CHECK (type IN ('CONTAINER_CLAIM', 'SHOP', 'PART', 'PHOTO', 'REVIEW', 'CHAT', 'MASTER'));
