-- ─────────────────────────── АДМИНКА: СПРАВОЧНИКИ (A5, A9) ───────────────────────────
-- Используемое не удаляется, а скрывается: is_active = false — нет в списках приложения,
-- но то, что уже выбрано (машины, магазины, заявки), продолжает работать.

ALTER TABLE brands ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
-- логотип, загруженный в админке (POST /media/photos purpose=BRAND); отдаётся по /api/v1/brands/{id}/logo
ALTER TABLE brands ADD COLUMN logo_media_id BIGINT REFERENCES media(id) ON DELETE SET NULL;

ALTER TABLE models ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
-- подпись вместо «модель + поколение», если она неудачная: «Camry 50 (XV50)»
ALTER TABLE models ADD COLUMN display_name VARCHAR(80);

ALTER TABLE categories ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE service_types ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;
-- радиус заявки по умолчанию: эвакуатору — шире
ALTER TABLE service_types ADD COLUMN default_radius_km SMALLINT NOT NULL DEFAULT 5
    CHECK (default_radius_km BETWEEN 1 AND 50);
UPDATE service_types SET default_radius_km = 10 WHERE code IN ('TOW_TRUCK', 'MOBILE_MASTER');

ALTER TABLE part_hints ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

-- синонимы правятся по одной паре: нужен id
ALTER TABLE search_synonyms ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE;

ALTER TABLE media DROP CONSTRAINT media_purpose_check;
ALTER TABLE media ADD CONSTRAINT media_purpose_check
    CHECK (purpose IN ('PART', 'SHOP', 'AVATAR', 'REQUEST', 'REPLY', 'MASTER', 'SERVICE', 'BRAND'));

-- Версия справочников: растёт при любой правке в админке. Клиент сверяет её и перекачивает справочники;
-- списки справочников ещё отдают ETag.
CREATE TABLE dictionary_version (
    id          SMALLINT    PRIMARY KEY CHECK (id = 1),
    version     BIGINT      NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO dictionary_version (id, version) VALUES (1, 1);
