-- ─────────────────────────── ПОЛЬЗОВАТЕЛИ ───────────────────────────
-- Перечисления храним строками с CHECK, а не нативными enum: проще миграции и маппинг JPA.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone         VARCHAR(16)  NOT NULL UNIQUE CHECK (phone ~ '^\+996[0-9]{9}$'),
    name          VARCHAR(120),
    -- текущий режим приложения; право продавца определяется членством в магазине
    role          VARCHAR(10)  NOT NULL DEFAULT 'BUYER' CHECK (role IN ('BUYER', 'SELLER')),
    lang          VARCHAR(2)   NOT NULL DEFAULT 'RU' CHECK (lang IN ('RU', 'KG')),
    -- администрация: админ рынка назначается суперадмином, суперадмин — вручную в базе
    admin_role    VARCHAR(12)  CHECK (admin_role IN ('MARKET_ADMIN', 'SUPERADMIN')),
    is_blocked    BOOLEAN      NOT NULL DEFAULT FALSE,
    -- момент выбора роли (экран 03); NULL — онбординг не пройден
    onboarded_at  TIMESTAMPTZ,
    last_seen_at  TIMESTAMPTZ,
    -- удаление аккаунта подтверждено по SMS; через 30 дней данные стираются, вход до этого — отмена
    deletion_requested_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_users_deletion ON users (deletion_requested_at) WHERE deletion_requested_at IS NOT NULL;

CREATE TABLE user_settings (
    user_id            BIGINT      PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    notify_replies     BOOLEAN     NOT NULL DEFAULT TRUE,
    notify_chat        BOOLEAN     NOT NULL DEFAULT TRUE,
    new_request_sound  BOOLEAN     NOT NULL DEFAULT TRUE,
    theme              VARCHAR(6)  NOT NULL DEFAULT 'SYSTEM' CHECK (theme IN ('LIGHT', 'DARK', 'SYSTEM'))
);

-- Refresh-токены непрозрачные: в БД только SHA-256, ротация при каждом обновлении.
CREATE TABLE refresh_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_refresh_tokens_user_active ON refresh_tokens (user_id) WHERE revoked_at IS NULL;

-- FCM-токены устройств
CREATE TABLE device_tokens (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token       VARCHAR(255) NOT NULL UNIQUE,
    platform    VARCHAR(8)   NOT NULL CHECK (platform IN ('IOS', 'ANDROID')),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_device_tokens_user ON device_tokens (user_id);

-- ─────────────────────────── ТЕХНИЧЕСКОЕ ───────────────────────────
-- Защита от дублей POST при обрыве связи (заголовок Idempotency-Key)
CREATE TABLE idempotency_keys (
    key          VARCHAR(80) PRIMARY KEY,
    user_id      BIGINT      NOT NULL,
    response     JSONB       NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_idempotency_keys_created ON idempotency_keys (created_at);
