-- ─────────────────────────── АДМИНКА: РАССЫЛКИ (A6) ───────────────────────────
-- Пуш-рассылка администрации. Аудитория — все / покупатели / продавцы / мастера с фильтрами
-- (марки, ряды, услуги). Текст на двух языках, получатель видит свой (users.lang). Отправка — фоновой задачей
-- батчами; в тихие часы 22:00–07:00 (Бишкек) не идёт: запланированное на это время переносится на 07:00.
CREATE TABLE broadcasts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audience          VARCHAR(7)    NOT NULL CHECK (audience IN ('ALL', 'BUYERS', 'SELLERS', 'MASTERS')),
    -- {"brandIds": [..], "rowIds": [..], "serviceTypes": [..]}
    filters           JSONB         NOT NULL DEFAULT '{}',
    title_ru          VARCHAR(80)   NOT NULL,
    title_kg          VARCHAR(80),
    body_ru           VARCHAR(500)  NOT NULL,
    body_kg           VARCHAR(500),
    status            VARCHAR(9)    NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT', 'SCHEDULED', 'SENDING', 'SENT', 'CANCELLED')),
    scheduled_at      TIMESTAMPTZ,
    started_at        TIMESTAMPTZ,
    sent_at           TIMESTAMPTZ,
    recipients_count  INT           NOT NULL DEFAULT 0,
    delivered_count   INT           NOT NULL DEFAULT 0,
    opened_count      INT           NOT NULL DEFAULT 0,
    -- докуда дошла отправка (получатели идут по возрастанию user_id) — после перезапуска продолжается отсюда
    progress_user_id  BIGINT        NOT NULL DEFAULT 0,
    created_by        BIGINT        REFERENCES users(id) ON DELETE SET NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_broadcasts_due ON broadcasts (scheduled_at) WHERE status IN ('SCHEDULED', 'SENDING');
CREATE INDEX idx_broadcasts_history ON broadcasts (created_at DESC, id DESC);

-- delivered_at — ушёл пуш (у пользователя есть устройство), opened_at — открыл из пуша
CREATE TABLE broadcast_recipients (
    broadcast_id  BIGINT       NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,
    user_id       BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    delivered_at  TIMESTAMPTZ,
    opened_at     TIMESTAMPTZ,
    PRIMARY KEY (broadcast_id, user_id)
);
