-- ─────────────────────────── СПРАВОЧНИК МАРОК И МОДЕЛЕЙ ───────────────────────────

CREATE TABLE brands (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug         VARCHAR(40)  NOT NULL UNIQUE,
    name         VARCHAR(60)  NOT NULL,
    -- путь к логотипу (NULL — клиент рисует букву placeholder цветом color)
    logo_url     VARCHAR(255),
    placeholder  VARCHAR(4)   NOT NULL,
    color        VARCHAR(7)   NOT NULL,
    -- 8 плиток «Популярные» на экранах 23 и 28, порядок — sort_order
    popular      BOOLEAN      NOT NULL DEFAULT FALSE,
    sort_order   SMALLINT     NOT NULL DEFAULT 100,
    -- народные названия для поиска: «мерс», «бэха»
    aliases      TEXT[]       NOT NULL DEFAULT '{}'
);

-- Модель = модель + поколение: «Camry 50», «E-класс W211». Годы — для проверки года машины и фитментов.
CREATE TABLE models (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id     BIGINT       NOT NULL REFERENCES brands(id),
    name         VARCHAR(60)  NOT NULL,
    generation   VARCHAR(30),
    year_from    SMALLINT,
    year_to      SMALLINT,               -- NULL — выпускается до сих пор
    sort_order   SMALLINT     NOT NULL DEFAULT 100,
    aliases      TEXT[]       NOT NULL DEFAULT '{}',
    CHECK (year_to IS NULL OR year_from IS NULL OR year_to >= year_from),
    UNIQUE NULLS NOT DISTINCT (brand_id, name, generation)
);
CREATE INDEX idx_models_brand ON models (brand_id, sort_order);

-- ─────────────────────────── ГАРАЖ ───────────────────────────

CREATE TABLE cars (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    brand_id     BIGINT       NOT NULL REFERENCES brands(id),
    model_id     BIGINT       NOT NULL REFERENCES models(id),
    year         SMALLINT     NOT NULL CHECK (year BETWEEN 1950 AND 2100),
    engine       VARCHAR(40),            -- «2.5 бензин»
    vin          VARCHAR(20),            -- VIN или номер кузова (японские авто)
    name         VARCHAR(40),            -- своё название машины («переименовать»)
    is_primary   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_cars_user ON cars (user_id, created_at);
-- у пользователя одна основная машина
CREATE UNIQUE INDEX uq_cars_primary ON cars (user_id) WHERE is_primary;

-- ─────────────────────────── СИД: 18 МАРОК (design/brands.json) ───────────────────────────

INSERT INTO brands (slug, name, logo_url, placeholder, color, popular, sort_order, aliases) VALUES
    ('toyota',        'Toyota',        '/assets/brands/toyota.png',        'T',   '#D92D2D', TRUE,  1, '{тойота,таёта,тоёта}'),
    ('lexus',         'Lexus',         '/assets/brands/lexus.png',         'L',   '#3F3F46', TRUE,  2, '{лексус}'),
    ('mercedes-benz', 'Mercedes-Benz', '/assets/brands/mercedes-benz.png', 'MB',  '#1F2937', TRUE,  3, '{мерс,мерседес,мерин,mercedes,benz,бенц}'),
    ('bmw',           'BMW',           NULL,                               'BMW', '#1C69D4', TRUE,  4, '{бмв,бэха,бэтэр,бумер}'),
    ('honda',         'Honda',         '/assets/brands/honda.png',         'H',   '#B91C1C', TRUE,  5, '{хонда}'),
    ('nissan',        'Nissan',        '/assets/brands/nissan.png',        'N',   '#6B7280', TRUE,  6, '{ниссан,нисан}'),
    ('hyundai',       'Hyundai',       NULL,                               'H',   '#0B3D91', TRUE,  7, '{хендай,хундай,хюндай,хёндэ}'),
    ('kia',           'Kia',           NULL,                               'K',   '#111827', TRUE,  8, '{киа}'),
    ('mitsubishi',    'Mitsubishi',    NULL,                               'M',   '#DC2626', FALSE, 100, '{митсубиси,мицубиси,митсубиши}'),
    ('subaru',        'Subaru',        NULL,                               'S',   '#1E40AF', FALSE, 100, '{субару}'),
    ('volkswagen',    'Volkswagen',    NULL,                               'VW',  '#1E3A8A', FALSE, 100, '{фольксваген,фольц,vw,вв}'),
    ('audi',          'Audi',          NULL,                               'A',   '#525252', FALSE, 100, '{ауди}'),
    ('mazda',         'Mazda',         NULL,                               'M',   '#374151', FALSE, 100, '{мазда}'),
    ('chevrolet',     'Chevrolet',     NULL,                               'C',   '#B8860B', FALSE, 100, '{шевроле,шевролет,шеви}'),
    ('daewoo',        'Daewoo',        NULL,                               'D',   '#2563EB', FALSE, 100, '{дэу,деу,дэо}'),
    ('lada',          'Lada',          NULL,                               'Л',   '#4B5563', FALSE, 100, '{лада,ваз,жигули}'),
    ('opel',          'Opel',          NULL,                               'O',   '#CA8A04', FALSE, 100, '{опель}'),
    ('ford',          'Ford',          NULL,                               'F',   '#1D4ED8', FALSE, 100, '{форд}');

-- ─────────────────────────── СИД: ПОПУЛЯРНЫЕ МОДЕЛИ ───────────────────────────
-- (марка, модель, поколение, годы, порядок, синонимы). Список расширяется через админку.

INSERT INTO models (brand_id, name, generation, year_from, year_to, sort_order, aliases)
SELECT b.id, m.name, m.generation, m.year_from, m.year_to, m.sort_order, m.aliases
FROM (VALUES
    ('toyota', 'Camry',              '30',    2001, 2006, 1, '{камри,xv30}'::text[]),
    ('toyota', 'Camry',              '40',    2006, 2011, 2, '{камри,xv40}'),
    ('toyota', 'Camry',              '50',    2011, 2017, 3, '{камри,xv50,xv55}'),
    ('toyota', 'Camry',              '70',    2017, 2024, 4, '{камри,xv70}'),
    ('toyota', 'Corolla',            'E120',  2000, 2007, 10, '{королла}'),
    ('toyota', 'Corolla',            'E150',  2006, 2013, 11, '{королла}'),
    ('toyota', 'Prius',              '20',    2003, 2009, 20, '{приус,nhw20}'),
    ('toyota', 'Prius',              '30',    2009, 2015, 21, '{приус,zvw30}'),
    ('toyota', 'RAV4',               'XA30',  2005, 2012, 30, '{рав4,рав}'),
    ('toyota', 'RAV4',               'XA40',  2012, 2018, 31, '{рав4,рав}'),
    ('toyota', 'Land Cruiser',       '100',   1998, 2007, 40, '{крузак,ленд крузер,лк}'),
    ('toyota', 'Land Cruiser',       '200',   2007, 2021, 41, '{крузак,ленд крузер,лк}'),
    ('toyota', 'Land Cruiser Prado', '120',   2002, 2009, 50, '{прадо}'),
    ('toyota', 'Land Cruiser Prado', '150',   2009, 2023, 51, '{прадо}'),
    ('toyota', 'Highlander',         'XU20',  2000, 2007, 60, '{хайлендер}'),
    ('toyota', 'Highlander',         'XU40',  2007, 2013, 61, '{хайлендер}'),
    ('toyota', 'Ipsum',              'M20',   2001, 2009, 70, '{ипсум}'),
    ('toyota', 'Estima',             'R50',   2006, 2019, 71, '{эстима}'),
    ('toyota', 'Alphard',            'H20',   2008, 2015, 72, '{альфард}'),

    ('lexus', 'RX', 'XU30', 2003, 2009, 1, '{рх,rx300,rx330,rx350}'),
    ('lexus', 'RX', 'AL10', 2008, 2015, 2, '{рх,rx350,rx450h}'),
    ('lexus', 'ES', 'XV40', 2006, 2012, 10, '{ес,es350}'),
    ('lexus', 'ES', 'XV60', 2012, 2018, 11, '{ес,es250,es350}'),
    ('lexus', 'GX', '470',  2002, 2009, 20, '{гх,gx470}'),
    ('lexus', 'GX', '460',  2009, 2023, 21, '{гх,gx460}'),
    ('lexus', 'LX', '470',  1998, 2007, 30, '{лх,lx470}'),
    ('lexus', 'LX', '570',  2007, 2021, 31, '{лх,lx570}'),
    ('lexus', 'IS', 'XE20', 2005, 2013, 40, '{ис}'),

    ('mercedes-benz', 'C-класс', 'W203', 2000, 2007, 1, '{цешка,c-class,c класс}'),
    ('mercedes-benz', 'C-класс', 'W204', 2007, 2014, 2, '{цешка,c-class,c класс}'),
    ('mercedes-benz', 'E-класс', 'W210', 1995, 2002, 10, '{ешка,глазастый,e-class,e класс}'),
    ('mercedes-benz', 'E-класс', 'W211', 2002, 2009, 11, '{ешка,e-class,e класс}'),
    ('mercedes-benz', 'E-класс', 'W212', 2009, 2016, 12, '{ешка,e-class,e класс}'),
    ('mercedes-benz', 'S-класс', 'W220', 1998, 2005, 20, '{эска,s-class,s класс}'),
    ('mercedes-benz', 'S-класс', 'W221', 2005, 2013, 21, '{эска,s-class,s класс}'),
    ('mercedes-benz', 'ML',      'W163', 1997, 2005, 30, '{мл,m-class}'),
    ('mercedes-benz', 'ML',      'W164', 2005, 2011, 31, '{мл,m-class}'),
    ('mercedes-benz', 'G-класс', 'W463', 1990, 2018, 40, '{гелик,гелендваген,g-class}'),
    ('mercedes-benz', 'Sprinter', NULL,  2006, 2018, 50, '{спринтер,w906}'),
    ('mercedes-benz', 'Vito',     NULL,  2003, 2014, 51, '{вито,w639}'),

    ('bmw', '3', 'E46', 1998, 2006, 1, '{тройка,3 series}'),
    ('bmw', '3', 'E90', 2005, 2012, 2, '{тройка,3 series}'),
    ('bmw', '3', 'F30', 2011, 2019, 3, '{тройка,3 series}'),
    ('bmw', '5', 'E39', 1995, 2004, 10, '{пятёрка,пятерка,5 series}'),
    ('bmw', '5', 'E60', 2003, 2010, 11, '{пятёрка,пятерка,5 series}'),
    ('bmw', '5', 'F10', 2009, 2017, 12, '{пятёрка,пятерка,5 series}'),
    ('bmw', 'X5', 'E53', 1999, 2006, 20, '{икс5,х5}'),
    ('bmw', 'X5', 'E70', 2006, 2013, 21, '{икс5,х5}'),
    ('bmw', 'X3', 'E83', 2003, 2010, 30, '{икс3,х3}'),

    ('honda', 'Fit',     'GD', 2001, 2008, 1, '{фит,jazz}'),
    ('honda', 'Fit',     'GE', 2007, 2013, 2, '{фит,jazz}'),
    ('honda', 'CR-V',    'RE', 2006, 2011, 10, '{црв,срв}'),
    ('honda', 'CR-V',    'RM', 2011, 2016, 11, '{црв,срв}'),
    ('honda', 'Accord',  'CL', 2002, 2008, 20, '{аккорд}'),
    ('honda', 'Accord',  'CU', 2008, 2013, 21, '{аккорд}'),
    ('honda', 'Odyssey', 'RB1', 2003, 2008, 30, '{одиссей}'),
    ('honda', 'Stepwgn', 'RG', 2005, 2009, 31, '{степвагон,степ}'),
    ('honda', 'Elysion', 'RR', 2004, 2013, 32, '{элюзион,элизион}'),
    ('honda', 'Civic',   'FD', 2005, 2011, 40, '{цивик,сивик}'),

    ('nissan', 'X-Trail', 'T30', 2000, 2007, 1, '{икстрейл,х-трейл,трейл}'),
    ('nissan', 'X-Trail', 'T31', 2007, 2014, 2, '{икстрейл,х-трейл,трейл}'),
    ('nissan', 'Teana',   'J31', 2003, 2008, 10, '{теана}'),
    ('nissan', 'Teana',   'J32', 2008, 2014, 11, '{теана}'),
    ('nissan', 'Patrol',  'Y61', 1997, 2010, 20, '{патрол}'),
    ('nissan', 'Patrol',  'Y62', 2010, NULL, 21, '{патрол}'),
    ('nissan', 'Murano',  'Z50', 2002, 2008, 30, '{мурано}'),
    ('nissan', 'Qashqai', 'J10', 2006, 2013, 31, '{кашкай}'),
    ('nissan', 'Almera',  'N16', 2000, 2006, 40, '{альмера}'),
    ('nissan', 'Tiida',   'C11', 2004, 2012, 41, '{тиида}'),

    ('hyundai', 'Sonata',   'NF', 2004, 2010, 1, '{соната}'),
    ('hyundai', 'Sonata',   'YF', 2009, 2014, 2, '{соната}'),
    ('hyundai', 'Sonata',   'LF', 2014, 2019, 3, '{соната}'),
    ('hyundai', 'Elantra',  'HD', 2006, 2011, 10, '{элантра}'),
    ('hyundai', 'Elantra',  'MD', 2010, 2016, 11, '{элантра}'),
    ('hyundai', 'Tucson',   'JM', 2004, 2010, 20, '{туссан,тусон}'),
    ('hyundai', 'Tucson',   'LM', 2009, 2015, 21, '{туссан,тусон,ix35}'),
    ('hyundai', 'Santa Fe', 'CM', 2006, 2012, 30, '{санта фе,сантафе}'),
    ('hyundai', 'Santa Fe', 'DM', 2012, 2018, 31, '{санта фе,сантафе}'),
    ('hyundai', 'Starex',   'H-1', 2007, 2021, 40, '{старекс}'),
    ('hyundai', 'Accent',   'MC', 2005, 2011, 50, '{акцент}'),
    ('hyundai', 'Solaris',  'RB', 2010, 2017, 51, '{солярис}'),

    ('kia', 'Sportage', 'KM', 2004, 2010, 1, '{спортейдж,спортаж}'),
    ('kia', 'Sportage', 'SL', 2010, 2016, 2, '{спортейдж,спортаж}'),
    ('kia', 'Sorento',  'BL', 2002, 2009, 10, '{соренто}'),
    ('kia', 'Sorento',  'XM', 2009, 2014, 11, '{соренто}'),
    ('kia', 'Rio',      'JB', 2005, 2011, 20, '{рио}'),
    ('kia', 'Optima',   'TF', 2010, 2015, 30, '{оптима,k5}'),
    ('kia', 'Cerato',   'TD', 2008, 2013, 31, '{церато,серато}'),
    ('kia', 'Carnival', 'VQ', 2006, 2014, 40, '{карнивал}'),

    ('mitsubishi', 'Pajero',       'III', 1999, 2006, 1, '{паджеро,пажеро}'),
    ('mitsubishi', 'Pajero',       'IV',  2006, 2021, 2, '{паджеро,пажеро}'),
    ('mitsubishi', 'Pajero Sport', 'II',  2008, 2016, 3, '{паджеро спорт}'),
    ('mitsubishi', 'Outlander',    'CU',  2001, 2006, 10, '{аутлендер}'),
    ('mitsubishi', 'Outlander',    'CW',  2005, 2012, 11, '{аутлендер}'),
    ('mitsubishi', 'Lancer',       'IX',  2000, 2010, 20, '{лансер}'),
    ('mitsubishi', 'Lancer',       'X',   2007, 2017, 21, '{лансер}'),
    ('mitsubishi', 'Delica',       'D:5', 2007, NULL, 30, '{делика}'),

    ('subaru', 'Forester', 'SG',    2002, 2008, 1, '{форестер}'),
    ('subaru', 'Forester', 'SH',    2007, 2013, 2, '{форестер}'),
    ('subaru', 'Legacy',   'BL/BP', 2003, 2009, 10, '{легаси}'),
    ('subaru', 'Outback',  'BP',    2003, 2009, 20, '{аутбек}'),
    ('subaru', 'Outback',  'BR',    2009, 2014, 21, '{аутбек}'),
    ('subaru', 'Impreza',  'GH',    2007, 2011, 30, '{импреза}'),

    ('volkswagen', 'Passat',      'B5', 1996, 2005, 1, '{пассат}'),
    ('volkswagen', 'Passat',      'B6', 2005, 2010, 2, '{пассат}'),
    ('volkswagen', 'Golf',        'IV', 1997, 2006, 10, '{гольф}'),
    ('volkswagen', 'Golf',        'V',  2003, 2009, 11, '{гольф}'),
    ('volkswagen', 'Polo',        '6R', 2009, 2017, 20, '{поло}'),
    ('volkswagen', 'Touareg',     '7L', 2002, 2010, 30, '{туарег}'),
    ('volkswagen', 'Transporter', 'T5', 2003, 2015, 40, '{транспортер,т5}'),

    ('audi', 'A4',  'B6', 2000, 2004, 1, '{а4}'),
    ('audi', 'A4',  'B7', 2004, 2008, 2, '{а4}'),
    ('audi', 'A6',  'C5', 1997, 2004, 10, '{а6}'),
    ('audi', 'A6',  'C6', 2004, 2011, 11, '{а6}'),
    ('audi', 'Q7',  '4L', 2005, 2015, 20, '{ку7}'),
    ('audi', '80',  'B4', 1991, 1996, 30, '{бочка}'),
    ('audi', '100', 'C4', 1990, 1994, 31, '{сотка}'),

    ('mazda', '6',     'GG', 2002, 2007, 1, '{мазда 6,шестёрка}'),
    ('mazda', '6',     'GH', 2007, 2012, 2, '{мазда 6,шестёрка}'),
    ('mazda', '3',     'BK', 2003, 2009, 10, '{мазда 3,тройка}'),
    ('mazda', 'CX-7',  NULL, 2006, 2012, 20, '{сх7,cx7}'),
    ('mazda', 'MPV',   'LY', 2006, 2016, 30, '{мпв}'),
    ('mazda', 'Demio', 'DY', 2002, 2007, 40, '{демио}'),

    ('chevrolet', 'Lacetti', NULL,   2004, 2013, 1, '{лачетти,лачети}'),
    ('chevrolet', 'Cobalt',  NULL,   2011, 2015, 2, '{кобальт}'),
    ('chevrolet', 'Captiva', NULL,   2006, 2018, 3, '{каптива}'),
    ('chevrolet', 'Spark',   'M300', 2010, 2015, 4, '{спарк}'),
    ('chevrolet', 'Malibu',  NULL,   2012, 2016, 5, '{малибу}'),

    ('daewoo', 'Nexia',  NULL, 1994, 2016, 1, '{нексия}'),
    ('daewoo', 'Matiz',  NULL, 1998, 2015, 2, '{матиз}'),
    ('daewoo', 'Lanos',  NULL, 1997, 2009, 3, '{ланос}'),
    ('daewoo', 'Gentra', NULL, 2013, 2015, 4, '{джентра,гентра}'),

    ('lada', '2107',      NULL, 1982, 2012, 1, '{семёрка,семерка,классика}'),
    ('lada', '2114',      NULL, 2001, 2013, 2, '{четырнадцатая,четырка}'),
    ('lada', 'Priora',    NULL, 2007, 2018, 3, '{приора}'),
    ('lada', 'Granta',    NULL, 2011, NULL, 4, '{гранта}'),
    ('lada', 'Niva 4x4',  NULL, 1977, NULL, 5, '{нива}'),
    ('lada', 'Vesta',     NULL, 2015, NULL, 6, '{веста}'),

    ('opel', 'Astra',  'G', 1998, 2009, 1, '{астра}'),
    ('opel', 'Astra',  'H', 2004, 2014, 2, '{астра}'),
    ('opel', 'Vectra', 'B', 1995, 2002, 10, '{вектра}'),
    ('opel', 'Vectra', 'C', 2002, 2008, 11, '{вектра}'),
    ('opel', 'Zafira', 'A', 1999, 2005, 20, '{зафира}'),
    ('opel', 'Omega',  'B', 1994, 2003, 30, '{омега}'),

    ('ford', 'Focus',    'II',  2004, 2011, 1, '{фокус}'),
    ('ford', 'Focus',    'III', 2011, 2019, 2, '{фокус}'),
    ('ford', 'Mondeo',   'III', 2000, 2007, 10, '{мондео}'),
    ('ford', 'Mondeo',   'IV',  2007, 2014, 11, '{мондео}'),
    ('ford', 'Escape',   NULL,  2007, 2012, 20, '{эскейп}'),
    ('ford', 'Transit',  NULL,  2006, 2014, 30, '{транзит}')
) AS m(brand_slug, name, generation, year_from, year_to, sort_order, aliases)
JOIN brands b ON b.slug = m.brand_slug;
