-- ─────────────────────────── КАРТА РЫНКА ───────────────────────────
-- Координаты — в системе схемы рынка (design/market-map.json): пиксели, ось Y вниз.

-- Версия схемы: всё, что рисуется, но не выбирается (граница, проходы, входы, улицы, подписи).
-- Клиент кэширует карту и перекачивает её, только если сменился version (ETag).
CREATE TABLE map_versions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        INT          NOT NULL UNIQUE,
    is_current     BOOLEAN      NOT NULL DEFAULT FALSE,
    boundary       JSONB        NOT NULL,   -- [[x,y],…]
    blocks         JSONB        NOT NULL,   -- невыбираемые блоки: СТО, администрация, парковка
    passages       JSONB        NOT NULL,   -- [{points, width, name:{kind,…}}] — из них граф маршрутов
    entrances      JSONB        NOT NULL,   -- [{x, y, label}]; первый — главный вход
    pois           JSONB        NOT NULL,   -- [{type: PARKING|TOILET, x, y, label}]
    streets        JSONB        NOT NULL,   -- улицы вокруг: [{name, polygon, labelX, labelY, rotate}]
    labels         JSONB        NOT NULL,   -- прочие подписи: [{text, x, y, rotate}]
    meters_per_px  NUMERIC(8,4) NOT NULL,   -- до GPS-калибровки — оценка, после — из аффинной матрицы
    geo_affine     JSONB,                   -- GPS → x,y (см. GeoCalibration); NULL — не откалибровано
    published_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_map_versions_current ON map_versions (is_current) WHERE is_current;

-- Ряд: код («14», «Ю», «Жайма 3»), геометрия — прямоугольник или многоугольник с осевой линией.
CREATE TABLE market_rows (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    label       VARCHAR(40)  NOT NULL,
    type        VARCHAR(5)   NOT NULL CHECK (type IN ('ROW', 'VROW', 'STALL')),
    -- {"rect":{x,y,w,h}} или {"polygon":[[x,y]…],"axis":[[x,y]…],"halfWidth":n}
    geometry    JSONB        NOT NULL,
    sort_order  SMALLINT     NOT NULL,     -- порядок в сетке рядов (экран 10а)
    qr_token    VARCHAR(32)  NOT NULL UNIQUE,  -- табличка в начале ряда
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE
);

-- Контейнер: место в ряду. Координаты не храним — считаются из геометрии ряда и числа мест на стороне.
CREATE TABLE containers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    row_id        BIGINT       NOT NULL REFERENCES market_rows(id),
    -- горизонтальные ряды: NORTH/SOUTH, вертикальные: WEST/EAST
    side          VARCHAR(5)   NOT NULL CHECK (side IN ('NORTH', 'SOUTH', 'WEST', 'EAST')),
    number        SMALLINT     NOT NULL CHECK (number > 0),
    pos_in_row    SMALLINT     NOT NULL CHECK (pos_in_row > 0),   -- 1 — у начала осевой линии
    qr_token      VARCHAR(32)  NOT NULL UNIQUE,                    -- наклейка на контейнере
    tenant_phone  VARCHAR(16),                                     -- номер арендатора из базы рынка
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,
    UNIQUE (row_id, side, number)
);
CREATE INDEX idx_containers_row ON containers (row_id, side, pos_in_row);

-- Опорные точки «GPS ↔ точка схемы» (углы рынка); по ним считается geo_affine.
CREATE TABLE geo_anchors (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat    NUMERIC(9,6) NOT NULL,
    lon    NUMERIC(9,6) NOT NULL,
    x      NUMERIC(8,2) NOT NULL,
    y      NUMERIC(8,2) NOT NULL,
    label  VARCHAR(60)
);

-- ─────────────────────────── СИД: СХЕМА v1 ИЗ market-map.json ───────────────────────────

INSERT INTO map_versions (version, is_current, boundary, blocks, passages, entrances, pois, streets, labels,
                          meters_per_px)
VALUES (1, TRUE,
'[[80,38],[835,35],[1110,375],[1330,843],[925,830],[948,1358],[238,1375]]',
'[
  {"kind":"anon","rect":{"x":140,"y":420,"w":385,"h":45}},
  {"kind":"shop","rect":{"x":92,"y":48,"w":50,"h":166}},
  {"kind":"shop","rect":{"x":162,"y":48,"w":56,"h":166}},
  {"kind":"shop","rect":{"x":238,"y":48,"w":44,"h":166}},
  {"kind":"shop","rect":{"x":302,"y":48,"w":52,"h":166}},
  {"kind":"shop","rect":{"x":376,"y":48,"w":58,"h":166}},
  {"kind":"shop","rect":{"x":456,"y":48,"w":106,"h":196}},
  {"kind":"anon","rect":{"x":740,"y":92,"w":90,"h":42}},
  {"kind":"admin","label":"Адм.","rect":{"x":658,"y":652,"w":58,"h":118}},
  {"kind":"parking","label":"Парковка","rect":{"x":140,"y":258,"w":400,"h":92}}
]',
'[
  {"points":[[584,34],[584,1221],[605,1318],[664,1382]],"width":23.5,"name":{"kind":"CENTRAL"}},
  {"points":[[648,98],[648,1104],[634,1123],[595,1127]],"width":13.9,"name":{"kind":"ALONG","rows":["Я","Ю"]}},
  {"points":[[723,93],[723,1379]],"width":13.9,"name":{"kind":"ALONG","rows":["С","Х"]}},
  {"points":[[723,641],[1149,641]],"width":13.9,"name":{"kind":"ALONG","rows":["Ц"]}},
  {"points":[[723,719],[1149,719]],"width":13.9,"name":{"kind":"BETWEEN","rows":["Ц","Л"]}},
  {"points":[[723,790],[1149,790]],"width":13.9,"name":{"kind":"BETWEEN","rows":["Л","Н"]}},
  {"points":[[1149,641],[1149,799]],"width":13.9,"name":{"kind":"ALONG","rows":["Ш"]}},
  {"points":[[814,790],[814,1168],[723,1264]],"width":13.9,"name":{"kind":"BETWEEN","rows":["Х","У"]}},
  {"points":[[199,467],[242,847],[271,1232],[292,1286],[632,1330],[675,1341]],"width":13.9,"name":{"kind":"WEST"}},
  {"points":[[543,355],[543,1072],[573,1125]],"width":13.9,"name":{"kind":"ROW_ENDS"}},
  {"points":[[199,467],[543,467]],"width":13.9,"name":{"kind":"ALONG","rows":["18"]}},
  {"points":[[207,537],[543,537]],"width":13.9,"name":{"kind":"BETWEEN","rows":["18","16"]}},
  {"points":[[216,615],[543,615]],"width":13.9,"name":{"kind":"BETWEEN","rows":["16","14"]}},
  {"points":[[224,689],[543,689]],"width":13.9,"name":{"kind":"BETWEEN","rows":["14","12"]}},
  {"points":[[232,761],[543,761]],"width":13.9,"name":{"kind":"BETWEEN","rows":["12","10"]}},
  {"points":[[241,836],[543,836]],"width":13.9,"name":{"kind":"BETWEEN","rows":["10","8"]}},
  {"points":[[246,903],[543,903]],"width":13.9,"name":{"kind":"BETWEEN","rows":["8","6"]}},
  {"points":[[251,974],[543,974]],"width":13.9,"name":{"kind":"BETWEEN","rows":["6","4"]}},
  {"points":[[257,1045],[543,1045]],"width":13.9,"name":{"kind":"BETWEEN","rows":["4","1"]}},
  {"points":[[262,1117],[579,1117]],"width":13.9,"name":{"kind":"BETWEEN","rows":["1","Жайма 1"]}},
  {"points":[[267,1186],[579,1186]],"width":13.9,"name":{"kind":"BETWEEN","rows":["Жайма 1","Жайма 3"]}},
  {"points":[[271,1261],[579,1261]],"width":13.9,"name":{"kind":"ALONG","rows":["Жайма 3"]}},
  {"points":[[226,366],[584,366]],"width":13.9,"name":{"kind":"PARKING"}},
  {"points":[[89,224],[445,224]],"width":13.9,"name":{"kind":"SERVICE"}},
  {"points":[[445,40],[445,224]],"width":13.9,"name":{"kind":"SERVICE"}},
  {"points":[[151,45],[151,224]],"width":10.7,"name":{"kind":"SERVICE"}},
  {"points":[[228,45],[228,224]],"width":10.7,"name":{"kind":"SERVICE"}},
  {"points":[[292,45],[292,224]],"width":10.7,"name":{"kind":"SERVICE"}},
  {"points":[[365,45],[365,224]],"width":10.7,"name":{"kind":"SERVICE"}}
]',
'[{"x":584,"y":34,"label":"Вход"},{"x":89,"y":224,"label":"Вход 2"},{"x":668,"y":1370,"label":"Вход 3"}]',
'[{"type":"PARKING","x":240,"y":304,"label":"Парковка"}]',
'[
  {"name":"УЛ. БИЛИМ","labelX":300,"labelY":21,"rotate":0,
   "polygon":[[-300,2],[870,2],[840,40],[-300,40]]},
  {"name":"УЛ. САДЫГАЛИЕВА","labelX":90,"labelY":720,"rotate":-84.5,
   "polygon":[[-40,-300],[40,-300],[95,0],[215,1700],[135,1700],[25,0]]},
  {"name":"УЛ. П. ЛУМУМБЫ","labelX":1212,"labelY":520,"rotate":62,
   "polygon":[[840,-300],[905,-300],[905,2],[1160,350],[1420,850],[1420,940],[1340,860],[1105,392],[842,42]]},
  {"name":null,"labelX":null,"labelY":null,"rotate":0,
   "polygon":[[-300,1380],[1420,1380],[1420,1420],[-300,1420]]}
]',
'[{"text":"ЦЕНТРАЛЬНЫЙ ПРОХОД","x":584,"y":900,"rotate":-90},{"text":"СТО и мастерские","x":330,"y":140,"rotate":0}]',
0.25);

-- Ряды в порядке сетки экрана 10а. Числа мест на сторону — оценка по длине ряда (≈19 px на место),
-- администрация уточняет их в админке (PUT /admin/market/rows/{id}/containers).
CREATE TEMPORARY TABLE seed_rows (code TEXT, label TEXT, type TEXT, geometry JSONB, sort_order INT, per_side INT);
INSERT INTO seed_rows VALUES
    ('18', 'Ряд 18', 'ROW',  '{"rect":{"x":219,"y":487,"w":306,"h":39}}', 1, 16),
    ('16', 'Ряд 16', 'ROW',  '{"rect":{"x":227,"y":548,"w":298,"h":56}}', 2, 16),
    ('14', 'Ряд 14', 'ROW',  '{"rect":{"x":236,"y":626,"w":289,"h":52}}', 3, 15),
    ('12', 'Ряд 12', 'ROW',  '{"rect":{"x":244,"y":700,"w":281,"h":50}}', 4, 15),
    ('10', 'Ряд 10', 'ROW',  '{"rect":{"x":252,"y":772,"w":273,"h":53}}', 5, 14),
    ('8',  'Ряд 8',  'ROW',  '{"rect":{"x":258,"y":847,"w":267,"h":45}}', 6, 14),
    ('6',  'Ряд 6',  'ROW',  '{"rect":{"x":263,"y":914,"w":262,"h":49}}', 7, 14),
    ('4',  'Ряд 4',  'ROW',  '{"rect":{"x":269,"y":985,"w":256,"h":49}}', 8, 13),
    ('1',  'Ряд 1',  'ROW',  '{"rect":{"x":274,"y":1056,"w":251,"h":50}}', 9, 13),
    ('З',  'Ряд З',  'VROW', '{"polygon":[[142,478],[189,478],[231,847],[259,1221],[213,1221],[183,847]],"axis":[[165.5,478],[207,847],[236,1221]],"halfWidth":23}', 10, 39),
    ('Ю',  'Ряд Ю',  'VROW', '{"rect":{"x":658,"y":848,"w":56,"h":480}}', 11, 25),
    ('Я',  'Ряд Я',  'VROW', '{"rect":{"x":658,"y":95,"w":54,"h":535}}', 12, 28),
    ('С',  'Ряд С',  'VROW', '{"rect":{"x":735,"y":145,"w":62,"h":485}}', 13, 26),
    ('Ж',  'Ряд Ж',  'VROW', '{"rect":{"x":805,"y":190,"w":60,"h":440}}', 14, 23),
    ('Д',  'Ряд Д',  'VROW', '{"rect":{"x":873,"y":205,"w":60,"h":425}}', 15, 22),
    ('В',  'Ряд В',  'VROW', '{"rect":{"x":941,"y":322,"w":60,"h":308}}', 16, 16),
    ('А',  'Ряд А',  'VROW', '{"polygon":[[878,95],[925,95],[1140,540],[1140,630],[1009,630],[1009,330]],"axis":[[901.5,100],[1060,440],[1075,625]],"halfWidth":30}', 17, 30),
    ('Ш',  'Ряд Ш',  'VROW', '{"rect":{"x":1162,"y":652,"w":62,"h":150}}', 18, 8),
    ('Ц',  'Ряд Ц',  'ROW',  '{"rect":{"x":742,"y":652,"w":393,"h":47}}', 19, 21),
    ('Л',  'Ряд Л',  'ROW',  '{"rect":{"x":742,"y":730,"w":393,"h":50}}', 20, 21),
    ('Н',  'Ряд Н',  'ROW',  '{"rect":{"x":742,"y":800,"w":393,"h":34}}', 21, 21),
    ('Х',  'Ряд Х',  'VROW', '{"rect":{"x":740,"y":848,"w":58,"h":300}}', 22, 16),
    ('У',  'Ряд У',  'VROW', '{"rect":{"x":826,"y":848,"w":56,"h":440}}', 23, 23),
    ('Жайма 1', 'Жайма 1', 'STALL', '{"rect":{"x":279,"y":1128,"w":246,"h":47}}', 24, 13),
    ('Жайма 3', 'Жайма 3', 'STALL', '{"rect":{"x":285,"y":1197,"w":240,"h":53}}', 25, 13);

INSERT INTO market_rows (code, label, type, geometry, sort_order, qr_token)
SELECT code, label, type, geometry, sort_order, replace(gen_random_uuid()::text, '-', '')
FROM seed_rows;

INSERT INTO containers (row_id, side, number, pos_in_row, qr_token)
SELECT r.id, s.side, g.n, g.n, replace(gen_random_uuid()::text, '-', '')
FROM market_rows r
JOIN seed_rows sr ON sr.code = r.code
CROSS JOIN LATERAL (VALUES
    (CASE WHEN r.type = 'VROW' THEN 'WEST' ELSE 'NORTH' END),
    (CASE WHEN r.type = 'VROW' THEN 'EAST' ELSE 'SOUTH' END)) AS s(side)
CROSS JOIN LATERAL generate_series(1, sr.per_side) AS g(n);

DROP TABLE seed_rows;
