-- ─────────────────────────── КАТЕГОРИИ ЗАПЧАСТЕЙ ───────────────────────────
-- Нужны магазину («Что продаю») и каталогу. Справочник ведёт суперадмин.

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        VARCHAR(40)  NOT NULL UNIQUE,
    name_ru     VARCHAR(60)  NOT NULL,
    name_kg     VARCHAR(60)  NOT NULL,
    sort_order  SMALLINT     NOT NULL DEFAULT 100
);

INSERT INTO categories (slug, name_ru, name_kg, sort_order) VALUES
    ('suspension',   'Ходовая',       'Жүрүүчү бөлүк',     1),
    ('brakes',       'Тормоза',       'Тормоздор',         2),
    ('engine',       'Двигатель',     'Кыймылдаткыч',      3),
    ('lights',       'Оптика',        'Оптика',            4),
    ('body',         'Кузов',         'Кузов',             5),
    ('electrics',    'Электрика',     'Электрика',         6),
    ('cooling',      'Охлаждение',    'Муздатуу',          7),
    ('transmission', 'Трансмиссия',   'Трансмиссия',       8),
    ('interior',     'Салон',         'Салон',             9),
    ('service',      'Фильтры и ТО',  'Чыпкалар жана ТО',  10);

-- ─────────────────────────── МАГАЗИНЫ ───────────────────────────

CREATE TABLE shops (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id              BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name                  VARCHAR(60)  NOT NULL,
    -- место магазина; один контейнер — один магазин
    container_id          BIGINT       NOT NULL REFERENCES containers(id),
    -- переезд: новое место ждёт проверки, магазин пока остаётся на старом
    pending_container_id  BIGINT       REFERENCES containers(id),
    status                VARCHAR(20)  NOT NULL DEFAULT 'PENDING_VERIFICATION'
                          CHECK (status IN ('PENDING_VERIFICATION', 'ACTIVE', 'BLOCKED')),
    block_reason          VARCHAR(300),
    verified_at           TIMESTAMPTZ,
    open_from             TIME         NOT NULL DEFAULT '08:00',
    open_to               TIME         NOT NULL DEFAULT '17:00',
    -- рабочие дни битами: Пн = 1, Вт = 2, … Вс = 64
    work_days             SMALLINT     NOT NULL DEFAULT 127 CHECK (work_days BETWEEN 1 AND 127),
    -- тумблер «Бокс закрыт» (экран 21)
    is_open               BOOLEAN      NOT NULL DEFAULT TRUE,
    phone                 VARCHAR(16),
    phone_visible         BOOLEAN      NOT NULL DEFAULT FALSE,
    rating                NUMERIC(2,1) NOT NULL DEFAULT 0,
    reviews_count         INT          NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CHECK (open_from < open_to),
    CHECK (pending_container_id IS NULL OR pending_container_id <> container_id)
);
CREATE UNIQUE INDEX uq_shops_container ON shops (container_id);
CREATE UNIQUE INDEX uq_shops_pending_container ON shops (pending_container_id) WHERE pending_container_id IS NOT NULL;
-- рассылка запросов и каталог берут только действующие магазины
CREATE INDEX idx_shops_active ON shops (id) WHERE status = 'ACTIVE' AND is_open;

-- Кто работает в боксе. Человек состоит не больше чем в одном магазине.
CREATE TABLE shop_members (
    shop_id     BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    user_id     BIGINT      NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    role        VARCHAR(5)  NOT NULL CHECK (role IN ('OWNER', 'STAFF')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (shop_id, user_id)
);

-- Марки, по которым магазин получает запросы (экран 23)
CREATE TABLE shop_brands (
    shop_id   BIGINT NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    brand_id  BIGINT NOT NULL REFERENCES brands(id),
    PRIMARY KEY (shop_id, brand_id)
);
CREATE INDEX idx_shop_brands_brand ON shop_brands (brand_id, shop_id);

-- «Что продаю» — для подсветки рядов по запчасти (экран 15)
CREATE TABLE shop_categories (
    shop_id      BIGINT NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    category_id  BIGINT NOT NULL REFERENCES categories(id),
    PRIMARY KEY (shop_id, category_id)
);
CREATE INDEX idx_shop_categories_category ON shop_categories (category_id, shop_id);

-- Проверка, что продавец действительно стоит в контейнере (ТЗ 7.2). GPS не храним — только итог.
CREATE TABLE shop_verifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id       BIGINT       NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    container_id  BIGINT       NOT NULL REFERENCES containers(id),
    method        VARCHAR(5)   NOT NULL CHECK (method IN ('QR', 'ADMIN', 'SMS')),
    status        VARCHAR(8)   NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    reason        VARCHAR(300),
    decided_by    BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    decided_at    TIMESTAMPTZ
);
CREATE INDEX idx_shop_verifications_shop ON shop_verifications (shop_id, created_at DESC);
-- очередь админки: заявки «подтвердите меня»
CREATE INDEX idx_shop_verifications_queue ON shop_verifications (created_at) WHERE status = 'PENDING';

CREATE TABLE favorite_shops (
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    shop_id     BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, shop_id)
);

-- ─────────────────────────── ЖАЛОБЫ ───────────────────────────
-- «Это мой контейнер» и дальше — жалобы на товары, фото, отзывы (модерация админом рынка).
CREATE TABLE complaints (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id    BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    type         VARCHAR(20)  NOT NULL CHECK (type IN ('CONTAINER_CLAIM', 'SHOP', 'PART', 'PHOTO', 'REVIEW')),
    target_id    BIGINT       NOT NULL,
    text         VARCHAR(1000),
    status       VARCHAR(8)   NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'RESOLVED', 'REJECTED')),
    resolution   VARCHAR(500),
    resolved_by  BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    resolved_at  TIMESTAMPTZ
);
CREATE INDEX idx_complaints_open ON complaints (created_at) WHERE status = 'OPEN';
