-- ─────────────────────────── ЗАПРОСЫ «НАЙТИ ЗАПЧАСТЬ» ───────────────────────────
-- Покупатель спрашивает деталь у продавцов своей марки (экраны 06, 07, 09, 20),
-- продавцы отвечают «Есть» / «Нет» (11, 12, 14). Фото запроса и ответа добавит модуль media.

CREATE TABLE part_requests (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id             BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    -- машину могут удалить из гаража — марка, модель и год лежат снимком
    car_id               BIGINT       REFERENCES cars(id) ON DELETE SET NULL,
    brand_id             BIGINT       NOT NULL REFERENCES brands(id),
    model_id             BIGINT       NOT NULL REFERENCES models(id),
    year                 SMALLINT     NOT NULL,
    text                 VARCHAR(200) NOT NULL CHECK (char_length(text) >= 3),
    -- чип подсказки («+ Колодки») — для статистики «Чаще всего спрашивают»
    category_id          BIGINT       REFERENCES categories(id),
    target               VARCHAR(6)   NOT NULL CHECK (target IN ('MARKET', 'ROW', 'SHOP')),
    target_row_id        BIGINT       REFERENCES market_rows(id),
    target_shop_id       BIGINT       REFERENCES shops(id) ON DELETE SET NULL,
    status               VARCHAR(7)   NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'CLOSED', 'EXPIRED')),
    -- «Купил» — у кого; остальные продавцы запрос больше не видят
    closed_with_shop_id  BIGINT       REFERENCES shops(id) ON DELETE SET NULL,
    closed_at            TIMESTAMPTZ,
    recipients_count     INT          NOT NULL DEFAULT 0,
    have_count           INT          NOT NULL DEFAULT 0,
    -- последняя рассылка (создание или «Отправить всему рынку») — от неё считаются 30 минут без ответа
    sent_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- когда сработал таймер «Пока никто не ответил» (экран 20)
    no_reply_at          TIMESTAMPTZ,
    -- создание, ответ, расширение; через 7 дней без действий запрос истекает
    last_activity_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CHECK ((target = 'ROW') = (target_row_id IS NOT NULL))
);
-- «Мои запросы» (05) и лимиты покупателя
CREATE INDEX idx_part_requests_buyer ON part_requests (buyer_id, created_at DESC);
-- таймеры «никто не ответил» и «истёк»
CREATE INDEX idx_part_requests_open ON part_requests (sent_at) WHERE status = 'OPEN';

-- Кому доставлен запрос: лента продавца (11), «без ответа» и время ответа в статистике (17)
CREATE TABLE request_recipients (
    request_id   BIGINT      NOT NULL REFERENCES part_requests(id) ON DELETE CASCADE,
    shop_id      BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    notified_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    seen_at      TIMESTAMPTZ,
    replied_at   TIMESTAMPTZ,
    PRIMARY KEY (request_id, shop_id)
);
CREATE INDEX idx_request_recipients_feed ON request_recipients (shop_id, notified_at DESC, request_id DESC);

-- Ответ магазина: один на запрос, первый ответ сотрудника засчитывается за весь бокс
CREATE TABLE request_replies (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id  BIGINT       NOT NULL REFERENCES part_requests(id) ON DELETE CASCADE,
    shop_id     BIGINT       NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    author_id   BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    answer      VARCHAR(8)   NOT NULL CHECK (answer IN ('HAVE', 'NOT_HAVE')),
    condition   VARCHAR(9)   CHECK (condition IN ('NEW', 'USED', 'ON_ORDER')),
    message     VARCHAR(300),
    price       INT          CHECK (price > 0),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    UNIQUE (request_id, shop_id),
    CHECK (answer = 'NOT_HAVE' OR condition IS NOT NULL)
);
-- экран 07: ответы «Есть» в порядке прихода
CREATE INDEX idx_request_replies_have ON request_replies (request_id, id) WHERE answer = 'HAVE';

-- ─────────────────────────── ОТЗЫВЫ ───────────────────────────
-- Оценка при закрытии запроса (09). Автор удалил аккаунт — отзыв остаётся анонимным.
CREATE TABLE reviews (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT       NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    buyer_id    BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    request_id  BIGINT       UNIQUE REFERENCES part_requests(id) ON DELETE SET NULL,
    stars       SMALLINT     NOT NULL CHECK (stars BETWEEN 1 AND 5),
    tags        TEXT[]       NOT NULL DEFAULT '{}',
    -- один ответ продавца на отзыв (экран 21)
    reply_text  VARCHAR(500),
    replied_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_reviews_shop ON reviews (shop_id, created_at DESC);
