-- ─────────────────────────── ЧАТЫ ───────────────────────────
-- Чат всегда между покупателем и магазином (не лично с продавцом): владелец и сотрудники бокса
-- видят один чат (экраны 08, 13, 16). Привязан к запросу; без запроса — прямой чат из профиля магазина.
-- Живая доставка — Centrifugo, источник истины — эти таблицы.

CREATE TABLE chats (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buyer_id                 BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    shop_id                  BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    request_id               BIGINT      REFERENCES part_requests(id) ON DELETE SET NULL,
    last_message_id          BIGINT,
    last_message_at          TIMESTAMPTZ,
    -- «прочитано» по сторонам: сотрудники бокса читают за весь магазин
    buyer_read_message_id    BIGINT      NOT NULL DEFAULT 0,
    shop_read_message_id     BIGINT      NOT NULL DEFAULT 0,
    -- статистика «Написали вам в чат» (17): покупатель отправил хотя бы одно сообщение
    buyer_first_message_at   TIMESTAMPTZ,
    -- «Заблокировать собеседника» из меню чата
    blocked_by_buyer         BOOLEAN     NOT NULL DEFAULT FALSE,
    blocked_by_shop          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- один чат на запрос и магазин; прямой чат — один на пару покупатель–магазин
CREATE UNIQUE INDEX uq_chats_request ON chats (buyer_id, shop_id, request_id) WHERE request_id IS NOT NULL;
CREATE UNIQUE INDEX uq_chats_direct ON chats (buyer_id, shop_id) WHERE request_id IS NULL;
-- списки чатов (16) у покупателя и у бокса
CREATE INDEX idx_chats_buyer ON chats (buyer_id, last_message_at DESC NULLS LAST, id DESC);
CREATE INDEX idx_chats_shop ON chats (shop_id, last_message_at DESC NULLS LAST, id DESC);
CREATE INDEX idx_chats_request ON chats (request_id) WHERE request_id IS NOT NULL;

CREATE TABLE messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id           BIGINT       NOT NULL REFERENCES chats(id) ON DELETE CASCADE,
    -- кто написал: сторона чата и конкретный человек (сотрудник бокса или покупатель)
    side              VARCHAR(6)   NOT NULL CHECK (side IN ('BUYER', 'SHOP', 'SYSTEM')),
    sender_id         BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    type              VARCHAR(8)   NOT NULL
                      CHECK (type IN ('TEXT', 'PHOTO', 'VOICE', 'VIDEO', 'REPLY', 'QUICK', 'SYSTEM')),
    text              VARCHAR(4000),
    -- быстрый ответ (QUICK) или системное событие (SYSTEM)
    code              VARCHAR(20),
    -- карточка ответа «Есть» (REPLY), карточка маршрута (QUICK ROUTE)
    payload           JSONB,
    media_key         VARCHAR(300),
    mime_type         VARCHAR(100),
    duration_seconds  INT          CHECK (duration_seconds IS NULL OR duration_seconds > 0),
    -- пики громкости 0..1 для голосовых
    waveform          JSONB,
    -- id с телефона: повтор из очереди отправки без сети не создаёт дубль
    client_id         VARCHAR(64),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_messages_chat ON messages (chat_id, id DESC);
CREATE UNIQUE INDEX uq_messages_client ON messages (chat_id, client_id) WHERE client_id IS NOT NULL;

ALTER TABLE chats ADD CONSTRAINT fk_chats_last_message
    FOREIGN KEY (last_message_id) REFERENCES messages(id) ON DELETE SET NULL;

-- Свои шаблоны ответов магазина («Есть в наличии, подходите», «Оригинал, гарантия 2 недели»)
CREATE TABLE reply_templates (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT        NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    text        VARCHAR(300)  NOT NULL CHECK (char_length(text) >= 1),
    sort_order  SMALLINT      NOT NULL DEFAULT 100,
    created_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_reply_templates_shop ON reply_templates (shop_id, sort_order, id);

-- Жалоба на чат из его меню
ALTER TABLE complaints DROP CONSTRAINT complaints_type_check;
ALTER TABLE complaints ADD CONSTRAINT complaints_type_check
    CHECK (type IN ('CONTAINER_CLAIM', 'SHOP', 'PART', 'PHOTO', 'REVIEW', 'CHAT'));
