-- ─────────────────────────── ФОТО ───────────────────────────
-- Загруженные фото (товары, дальше — аватары и фото места). Сервер пережимает в два размера:
-- 1080 px (карточка, карусель) и 320 px (сетка, превью); перекодирование убирает EXIF и геометку.

CREATE TABLE media (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id     BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    purpose      VARCHAR(8)   NOT NULL CHECK (purpose IN ('PART', 'SHOP', 'AVATAR', 'REQUEST')),
    key_1080     VARCHAR(300) NOT NULL,
    key_320      VARCHAR(300) NOT NULL,
    width        INT          NOT NULL,
    height       INT          NOT NULL,
    size_bytes   BIGINT       NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_media_owner ON media (owner_id, created_at DESC);

-- ─────────────────────────── КАТАЛОГ ───────────────────────────
-- Запчасти продавцов (экраны 24–30). Черновик (DRAFT) можно сохранять неполным,
-- публикация (ACTIVE) требует всех обязательных полей, фото и хотя бы одной машины.

CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE parts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id       BIGINT        NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    status        VARCHAR(8)    NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'ACTIVE', 'ARCHIVED')),
    title         VARCHAR(120),
    category_id   BIGINT        REFERENCES categories(id),
    condition     VARCHAR(9)    CHECK (condition IN ('NEW', 'USED', 'ON_ORDER')),
    price         INT           CHECK (price > 0),
    -- 0 — «Нет в наличии»
    quantity      INT           NOT NULL DEFAULT 1 CHECK (quantity >= 0),
    manufacturer  VARCHAR(60),
    oem_number    VARCHAR(40),
    -- номер детали без пробелов и дефисов, заглавными: поиск «90919 01253» = «9091901253»
    oem_norm      VARCHAR(40),
    side          VARCHAR(5)    CHECK (side IN ('LEFT', 'RIGHT')),
    position      VARCHAR(5)    CHECK (position IN ('FRONT', 'REAR')),
    views_count   INT           NOT NULL DEFAULT 0,
    published_at  TIMESTAMPTZ,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- полнотекстовый поиск: русская морфология по названию + как есть (кыргызский, латиница, номера)
    search_tsv    TSVECTOR GENERATED ALWAYS AS (
                      setweight(to_tsvector('russian', coalesce(title, '')), 'A')
                      || setweight(to_tsvector('simple', coalesce(title, '')), 'A')
                      || setweight(to_tsvector('simple', coalesce(manufacturer, '')), 'B')
                      || setweight(to_tsvector('simple', coalesce(oem_norm, '')), 'A')) STORED,
    CHECK (status = 'DRAFT' OR (title IS NOT NULL AND category_id IS NOT NULL AND condition IS NOT NULL
                                AND price IS NOT NULL))
);
CREATE INDEX idx_parts_shop ON parts (shop_id, status, created_at DESC, id DESC);
CREATE INDEX idx_parts_active_price ON parts (price, id) WHERE status = 'ACTIVE';
CREATE INDEX idx_parts_search ON parts USING GIN (search_tsv);
-- опечатки: «амартизатор» ≈ «амортизатор»
CREATE INDEX idx_parts_title_trgm ON parts USING GIN (lower(title) gin_trgm_ops);
CREATE INDEX idx_parts_oem_trgm ON parts USING GIN (oem_norm gin_trgm_ops);

-- 1–6 фото по порядку, первое (sort = 0) — «Главное». Ключ по позиции: перестановка — просто UPDATE.
CREATE TABLE part_photos (
    part_id   BIGINT NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
    sort      INT    NOT NULL CHECK (sort BETWEEN 0 AND 5),
    media_id  BIGINT NOT NULL REFERENCES media(id),
    PRIMARY KEY (part_id, sort)
);

-- «Подходит к машинам»: марка обязательна; модель NULL — «Все модели»; годы NULL — без ограничения
CREATE TABLE part_fitments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_id    BIGINT   NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
    brand_id   BIGINT   NOT NULL REFERENCES brands(id),
    model_id   BIGINT   REFERENCES models(id),
    year_from  SMALLINT,
    year_to    SMALLINT,
    CHECK (year_from IS NULL OR year_to IS NULL OR year_from <= year_to)
);
CREATE INDEX idx_part_fitments_part ON part_fitments (part_id);
CREATE INDEX idx_part_fitments_car ON part_fitments (brand_id, model_id, part_id);

CREATE TABLE favorite_parts (
    user_id     BIGINT      NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    part_id     BIGINT      NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, part_id)
);

-- Просмотры карточки по дням: «Покупатели посмотрели ваши запчасти 214 раз за неделю» (24), статистика (17)
CREATE TABLE part_views_daily (
    part_id  BIGINT NOT NULL REFERENCES parts(id) ON DELETE CASCADE,
    day      DATE   NOT NULL,
    views    INT    NOT NULL DEFAULT 0,
    PRIMARY KEY (part_id, day)
);

-- Синонимы поиска (ведёт суперадмин): запрос «стойка» ищет и «амортизатор». Пары в обе стороны.
CREATE TABLE search_synonyms (
    term     VARCHAR(40) NOT NULL,
    synonym  VARCHAR(40) NOT NULL,
    PRIMARY KEY (term, synonym)
);
WITH pairs (a, b) AS (VALUES
    ('стойка', 'амортизатор'),
    ('колодки', 'колодка'),
    ('фара', 'оптика'),
    ('радиатор', 'охлаждение'),
    ('глушитель', 'выхлоп'),
    ('ступица', 'подшипник'),
    ('шаровая', 'шарнир'),
    ('рулевая', 'рейка'),
    ('генератор', 'динамо'),
    ('пыльник', 'чехол'),
    ('кпп', 'коробка'),
    ('акпп', 'автомат'),
    ('свеча', 'свечи'),
    ('тормоз', 'тормоза'))
INSERT INTO search_synonyms (term, synonym)
SELECT a, b FROM pairs
UNION
SELECT b, a FROM pairs;

-- ─────────────────────────── СВЯЗИ С ЗАПРОСАМИ И ЧАТОМ ───────────────────────────
-- «Приложить товар из каталога» к ответу «Есть» (ТЗ 10.2)
ALTER TABLE request_replies ADD COLUMN part_id BIGINT REFERENCES parts(id) ON DELETE SET NULL;

-- «Написать» с карточки запчасти: карточка товара в чате (ТЗ 5.3)
ALTER TABLE messages DROP CONSTRAINT messages_type_check;
ALTER TABLE messages ADD CONSTRAINT messages_type_check
    CHECK (type IN ('TEXT', 'PHOTO', 'VOICE', 'VIDEO', 'REPLY', 'QUICK', 'SYSTEM', 'PART'));
